name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build -t matheusmc/golang-example:$GITHUB_SHA .
        docker push matheusmc/golang-example:$GITHUB_SHA
        
    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker stop golang >/dev/null 2>&1 || true
          docker rm golang >/dev/null 2>&1 || true
          docker pull matheusmc/golang-example:$GITHUB_SHA
          docker run -d -p 8080:8080 --name golang matheusmc/golang-example:$GITHUB_SHA

