name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      run: |
        docker build -t seu-usuario-dockerhub/nome-da-imagem:$GITHUB_SHA .
        docker push seu-usuario-dockerhub/nome-da-imagem:$GITHUB_SHA
        
    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker stop sua-aplicacao || true
          docker rm sua-aplicacao || true
          docker pull seu-usuario-dockerhub/nome-da-imagem:$GITHUB_SHA
          docker run -d -p 8080:8080 --name sua-aplicacao seu-usuario-dockerhub/nome-da-imagem:$GITHUB_SHA
